title: MP4Fish
description: >-
  A BiodivTransform funded project aiming to foster fishermen agency in the creation of Marine Protected Areas.
baseurl: ""
url: "https://Loic-sanchez.github.io"

theme: minima

author:
  name: MP4Fish Consortium

nav_pages:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Team
    url: /team
  - title: News & Results
    url: /news
  - title: Contact
    url: /contact

plugins:
  - jekyll-feed
  - jekyll-seo-tag
